---
apiVersion: v1
kind: Service
metadata: 
  name: backend-service
  labels:
    app: backend-app
spec:
  port:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: backend-app       
...